---
title: "Random Forest"
output:
  word_document: default
  pdf_document: default
date: "2025-05-12"
---

```{r, message=FALSE}
library(openxlsx)
library(readxl)
library(dplyr)
library(data.table)
library(randomForestSRC)
library(randomForest)
library(PRROC)
library(pROC)
library(caret)
library(xgboost)
library(DALEX)
library(iml)
library(ranger)
```


```{r}
af_data <- read.xlsx("ssc.xlsx")
```

```{r}

make_afib_flag_df <- function(data, cutoff_days) {
  data %>%
    mutate(
      afib_by_cutoff = as.integer(
        !is.na(time_to_outcome_afib_aflutter_new_post) &
          time_to_outcome_afib_aflutter_new_post <= cutoff_days))}

make_bloodwork_flags <- function(data, ..., prefix = "observed_") {
  data %>%
    mutate(across(c(...),
                  ~ as.integer(!is.na(.x)),
                  .names = paste0(prefix, "{.col}")))}

names(af_data) <- gsub("obstructive _sleep_apnea_icd10",
                       "obstructive_sleep_apnea_icd10", names(af_data))

df_flags <- make_bloodwork_flags(af_data,
                                 troponin_t_hs_peri_highest,
                                 crp_high_sensitive_peri,
                                 tsh_peri, hga1c_peri_highest, 
                                 glucose_fasting_peri_highest,
                                 hgb_peri, hct_peri, rdw_peri,
                                 wbc_peri, plt_peri, inr_peri, 
                                 ptt_peri, esr_peri,
                                 albumin_peri, alkaline_phophatase_peri,
                                 alanine_transaminase_peri, 
                                 aspartate_transaminase_peri,
                                 bilirubin_total_peri, bilirubin_direct_peri,
                                 urea_peri, creatinine_peri,
                                 urine_alb_cr_ratio_peri,
                                 sodium_peri,potassium_peri, chloride_peri,
                                 ck_peri,
                                 NTproBNP_peri_highest, 
                                 glucose_random_peri_highest,
                                 tchol_peri_highest, ldl_peri_highest, 
                                 hdl_peri_lowest, tg_peri_highest,
                                 iron_peri, tibc_peri, ferritin_peri)

df180 <- make_afib_flag_df(df_flags, cutoff_days = 180)
df365 <- make_afib_flag_df(df_flags, cutoff_days = 365)

vars_to_remove <- c(
  "troponin_t_hs_peri_highest",
  "potassium_peri",
  "crp_high_sensitive_peri",
  "tsh_peri", 
  "hga1c_peri_highest",
  "glucose_fasting_peri_highest",
  "hgb_peri", "hct_peri", 
  "rdw_peri", "wbc_peri",
  "plt_peri", "inr_peri",
  "ptt_peri", "esr_peri", 
  "albumin_peri",
  "alkaline_phophatase_peri",
  "alanine_transaminase_peri", 
  "aspartate_transaminase_peri",
  "bilirubin_total_peri",
  "bilirubin_direct_peri", 
  "urea_peri",
  "creatinine_peri",
  "urine_alb_cr_ratio_peri",
  "sodium_peri", 
  "chloride_peri",
  "ck_peri",
  "NTproBNP_peri_highest",
  "glucose_random_peri_highest", 
  "tchol_peri_highest",
  "ldl_peri_highest",
  "hdl_peri_lowest",
  "tg_peri_highest", 
  "iron_peri",
  "tibc_peri",
  "ferritin_peri",
  "anti_platelet_oral_non_asa_any_peri",
  "anti_coagulant_oral_any_peri",
  "nitrates_any_peri", 
  "ranolazine_peri",
  "acei_peri",
  "arb_peri",
  "arni_entresto_peri",
  "beta_blocker_any_peri",
  "ivabradine_peri",
  "ccb_dihydro_peri", 
  "ccb_non_dihydro_peri",
  "diuretic_loop_peri",
  "diuretic_thiazide_peri",
  "diuretic_low_ceiling_non_thiazide_peri",
  "diuretic_metolazone_peri", 
  "diuretic_indapamide_peri",
  "diuretic_mra_peri",
  "diuretic_vasopressin_antagonist_peri",
  "anti_arrhythmic_any_peri", 
  "anti_arrhythmic_amiodarone_peri",
  "anti_arrhythmic_disopyramide_peri",
  "digoxin_peri",
  "amyloid_therapeutics_tafamidis_peri", 
  "amyloid_therapeutics_diflunisal_peri",
  "amyloid_therapeutics_patisiran_peri",
  "amyloid_therapeutics_inotersen_peri",
  "lipid_statin_peri", 
  "lipid_fibrate_peri",
  "lipid_ezetimibe_peri",
  "lipid_PCKSK9_peri",
  "lipid_other_peri",
  "glucose_insulin_peri",
  "glucose_glp_1_agonsist_peri", 
  "glucose_ohg_biguanide_peri",
  "glucose_ohg_alphagluc_peri", 
  "glucose_ohg_dpp_4_peri", 
  "glucose_ohg_sglt_2_peri", 
  "glucose_ohg_thiazolidine_peri",
  "glucose_ohg_repaglinide_peri",
  "glucose_ohg_sulfonylurea_peri",
  "glucose_ohg_other_peri", 
  "smoking_cessation_oral_peri",
  "smoking_cessation_nicotine_replacement_peri",
  "patient_id",
  "outcome_afib_aflutter_new_post", 
  "time_to_outcome_afib_aflutter_new_post",
  "follow_up_duration",
  "time_to_outcome_all_cause_death",
  "outcome_all_cause_death")

# Include ande exclude ecg data from each df
df180_ecg <- df180 %>%
  select(-all_of(vars_to_remove)) %>%
  na.omit() # reduces sample size by 936 

df180_noecg <- df180_ecg %>%
  select(-starts_with("ecg"))

df365_ecg <- df365 %>%
  select(-all_of(vars_to_remove)) %>%
  na.omit()

df365_noecg <- df365_ecg %>%
  select(-starts_with("ecg"))
```


```{r, message=FALSE, warning=FALSE}
#Random Forest – 180 Days Without ECG
set.seed(123)
trainIndex_rf <- createDataPartition(df180_noecg$afib_by_cutoff, p = 0.8, list = FALSE)
train_rf_180_noecg <- df180_noecg[trainIndex_rf, ]
test_rf_180_noecg <- df180_noecg[-trainIndex_rf, ]


# Train RF model
rf_model_180_noecg <- ranger(
  afib_by_cutoff ~ ., 
  data = train_rf_180_noecg,
  num.trees = 100,
  probability = TRUE,
  respect.unordered.factors = "partition",
  na.action = "na.omit"
)

# Predict
rf_pred_180_noecg <- predict(rf_model_180_noecg, data = test_rf_180_noecg)$predictions[,2]
rf_class_180_noecg <- ifelse(rf_pred_180_noecg > 0.5, 1, 0)
actual_rf_180_noecg <- test_rf_180_noecg$afib_by_cutoff

# Confusion Matrix
confusionMatrix(as.factor(rf_class_180_noecg), as.factor(actual_rf_180_noecg))

# Precision-Recall
pr_rf_180_noecg <- pr.curve(
  scores.class0 = rf_pred_180_noecg[actual_rf_180_noecg == 1],
  scores.class1 = rf_pred_180_noecg[actual_rf_180_noecg == 0],
  curve = TRUE
)
plot(pr_rf_180_noecg, main = "PR Curve - RF 180 Days No ECG", col = "darkgreen")

get_calib_data <- function(pred, actual, bins = 10) {
  calib_df <- data.frame(pred = pred, actual = actual)

  breaks <- unique(quantile(calib_df$pred, probs = seq(0, 1, length.out = bins + 1)))
  
  if (length(breaks) < 3) {
    stop("Not enough unique predicted values to form bins.")
  }

  calib_df$bin <- cut(calib_df$pred, breaks = breaks, include.lowest = TRUE)

  calib_summary <- calib_df %>%
    group_by(bin) %>%
    summarise(
      bin_midpoint = mean(pred),
      observed = mean(actual),
      .groups = "drop"
    )
  return(calib_summary)
}

# Calibration
rf_calib_180_noecg <- get_calib_data(rf_pred_180_noecg, actual_rf_180_noecg)
ggplot(rf_calib_180_noecg, aes(x = bin_midpoint, y = observed)) +
  geom_point() + geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
  labs(title = "Calibration - RF 180 No ECG", x = "Predicted Probability", y = "Observed Rate") +
  theme_minimal()

# ROC
rf_roc_180_noecg <- roc(actual_rf_180_noecg, rf_pred_180_noecg)
plot(rf_roc_180_noecg, col = "blue", main = "ROC - RF 180 Days No ECG")
auc(rf_roc_180_noecg)

#SHAP
predict_rf_prob_noecg <- function(model, newdata) {
  pred <- predict(model, data = newdata)$predictions
  return(pred[, 2])
}

predictor_rf_noecg <- Predictor$new(
  model = rf_model_180_noecg,
  data = train_rf_180_noecg[, -which(names(train_rf_180_noecg) == "afib_by_cutoff")],
  y = train_rf_180_noecg$afib_by_cutoff,
  predict.fun = predict_rf_prob_noecg,
  class = "1")

shap_rf_noecg <- Shapley$new(
  predictor_rf_noecg,
  x.interest = test_rf_180_noecg[1, -which(names(test_rf_180_noecg) == "afib_by_cutoff")]
)

plot(shap_rf_noecg)
```



```{r, message=FALSE, warning=FALSE}
#Random Forest with ECG
set.seed(123)
trainIndex_rf_ecg <- createDataPartition(df180_ecg$afib_by_cutoff, p = 0.8, list = FALSE)
train_rf_180_ecg <- df180_ecg[trainIndex_rf_ecg, ]
test_rf_180_ecg <- df180_ecg[-trainIndex_rf_ecg, ]

rf_model_180_ecg <- ranger(
  afib_by_cutoff ~ ., 
  data = train_rf_180_ecg,
  num.trees = 100,
  probability = TRUE,
  respect.unordered.factors = "partition",
  na.action = "na.omit"
)

rf_pred_180_ecg <- predict(rf_model_180_ecg, data = test_rf_180_ecg)$predictions[,2]
rf_class_180_ecg <- ifelse(rf_pred_180_ecg > 0.5, 1, 0)
actual_rf_180_ecg <- test_rf_180_ecg$afib_by_cutoff

confusionMatrix(as.factor(rf_class_180_ecg), as.factor(actual_rf_180_ecg))

pr_rf_180_ecg <- pr.curve(
  scores.class0 = rf_pred_180_ecg[actual_rf_180_ecg == 1],
  scores.class1 = rf_pred_180_ecg[actual_rf_180_ecg == 0],
  curve = TRUE
)
plot(pr_rf_180_ecg, main = "PR Curve - RF 180 Days ECG", col = "darkgreen")

rf_calib_180_ecg <- get_calib_data(rf_pred_180_ecg, actual_rf_180_ecg)
ggplot(rf_calib_180_ecg, aes(x = bin_midpoint, y = observed)) +
  geom_point() + geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "gray") +
  labs(title = "Calibration - RF 180 ECG", x = "Predicted Probability", y = "Observed Rate") +
  theme_minimal()

rf_roc_180_ecg <- roc(actual_rf_180_ecg, rf_pred_180_ecg)
plot(rf_roc_180_ecg, col = "blue", main = "ROC - RF 180 Days ECG")
auc(rf_roc_180_ecg)

#SHAP
predict_rf_prob <- function(model, newdata) {
  pred <- predict(model, data = newdata)$predictions
  return(pred[, 2])  # 2nd column = prob of class 1
}


predictor_rf <- Predictor$new(
  model = rf_model_180_ecg,
  data = train_rf_180_ecg[, -which(names(train_rf_180_ecg) == "afib_by_cutoff")],
  y = train_rf_180_ecg$afib_by_cutoff,
  predict.fun = predict_rf_prob
)

shap_rf <- Shapley$new(predictor_rf, x.interest = test_rf_180_ecg[1, -which(names(test_rf_180_ecg) == "afib_by_cutoff")])
plot(shap_rf)
```

